defaults: &defaults
  working_directory: ~/code
  docker:
    - image: circleci/android:api-27-alpha
  environment:
    JVM_OPTS: -Xmx3200m

version: 2

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Test - Build - Release
          command: ./scripts/ci/build.sh $CIRCLE_BRANCH
      - store_artifacts:
          path: app/build/outputs/apk/staging/release/app-staging-release.apk
          destination: app-staging-release.apk
      - store_artifacts:
          path: app/build/outputs/mapping/staging/release/mapping.txt
          destination: staging-mapping.txt
      - store_artifacts:
          path: app/build/outputs/apk/production/release/app-production-release-unsigned.apk
          destination: app-production-release-unsigned.apk
      - store_artifacts:
          path: app/build/outputs/mapping/production/release/mapping.txt
          destination: production-mapping.txt